### PR TITLE
Fix routing with moved attributes

### LINKED ISSUE #763: SyliusCrudRoutes: lost routes after last update
**Sylius version affected**: 1.11-dev

**Description**  
I did an update from 1.11-alpha1 to 1.11-dev because of new driver parameter with AsResource. After that, I had an error in my panel: `Unable to generate a URL for the named route "sylius_backend_admin_user_index" as such route does not exist.`

Problem was solved by using the new namespace `Sylius\Resource\Annotation\SyliusCrudRoutes` but it is a regression.

**Steps to reproduce**  
Just use the deprecated namespace `Sylius\Component\Resource\Annotation\SyliusCrudRoutes` instead of the new one.

### PR DESCRIPTION
**Pull request by loic425**
| Q               | A
| --------------- | -----
| Bug fix?        | yes (but on 1.11 branch only)
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #763 
| License         | MIT

### CODE REVIEW

File: tests/Application/src/Entity/Route/ShowBookWithLegacyAttribute.php [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+use JMS\Serializer\Annotation as Serializer;
+use Sylius\Component\Resource\Annotation\SyliusRoute;
+
+/**
+ * @Serializer\ExclusionPolicy("all")
+ */
+#[SyliusRoute(
+    name: 'show_book_with_legacy_attribute',
+    path: '/book/{id}',
+    controller: 'app.controller.book:showAction',
```
Comment (diimpp) [inline tests/Application/src/Entity/Route/ShowBookWithLegacyAttribute.php]: Symfony uses `::` since SF5 if it's applicable here
```suggestion
    controller: 'app.controller.book::showAction',
```

File: tests/Bundle/Routing/RoutesAttributesLoaderTest.php [hunk 2]
```diff
@@ -544,4 +544,24 @@ public function it_generates_routes_from_resource_with_return_content(): void
...
+
+        $attributesLoader = $container->get('sylius.routing.loader.routes_attributes');
+
+        $routesCollection = $attributesLoader->__invoke();
+
+        $route = $routesCollection->get('show_book_with_legacy_attribute');
+        $this->assertNotNull($route);
+        $this->assertEquals('/book/{id}', $route->getPath());
+        $this->assertEquals([
+            '_controller' => 'app.controller.book:showAction',
```
Comment (diimpp) [inline tests/Bundle/Routing/RoutesAttributesLoaderTest.php]: If it's applicable here
```suggestion
            '_controller' => 'app.controller.book::showAction',
```

**Review by diimpp — APPROVED** [review]

**Review by diimpp — APPROVED** [review]

**Review by oallain — APPROVED** [review]

**Review by lchrusciel — APPROVED** [review]

**Comment by lchrusciel** [comment]
Thank you, @loic425!
