### PR TITLE
[Symfony 6] Fix submitting a form

### LINKED ISSUE #475: Symfony 6.1 form submit error
**Sylius version affected**: v1.10.0-ALPHA.1 

**Description**  
With Symfony 6.1 forms cannot be submitted due to this error "Input value "form" contains a non-scalar value.". When debugging the value inside InputBag contains an array with all form fields.

This was the deprecation before:

```
User Deprecated: Since symfony/http-foundation 5.1: Retrieving a non-string value from "Symfony\Component\HttpFoundation\InputBag::get()" is deprecated, and will throw a "Symfony\Component\HttpFoundation\Exception\BadRequestException" exception in Symfony 6.0, use "Symfony\Component\HttpFoundation\InputBag::all($key)" instead.

class: HttpFoundationRequestHandler, line 88
```

**Possible Solution**  

Change https://github.com/Sylius/SyliusResourceBundle/blob/v1.10.0-ALPHA.1/src/Bundle/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php#L89 too
```
$params = $request->request->all($name); or $params = $request->request->all()[$name]
```

### PR DESCRIPTION
**Pull request by loic425**
| Q               | A
| --------------- | -----
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | Fixes #475 
| License         | MIT

Before 
Capture d’écran du 2022-08-23 12-34-12

https://github.com/Sylius/SyliusResourceBundle/runs/7976112788?check_suite_focus=true#step:11:25

After
https://github.com/Sylius/SyliusResourceBundle/runs/7976227254?check_suite_focus=true

### CODE REVIEW

**Review by Roshyo — APPROVED** [review]

File: src/Bundle/test/src/Tests/Controller/ScienceBookUiTest.php [hunk 1]
```diff
@@ -56,6 +57,60 @@ public function it_allows_indexing_books(): void
...
+
+        $this->assertResponseRedirects(null, expectedCode: Response::HTTP_FOUND);
+
+        /** @var ScienceBook $book */
+        $book = static::getContainer()->get('app.repository.science_book')->findOneBy(['title' => $newBookTitle]);
+
+        $this->assertNotNull($book);
+        $this->assertSame($newBookTitle, $book->getTitle());
+        $this->assertSame($newBookAuthorFirstName, $book->getAuthorFirstName());
+        $this->assertSame($newBookAuthorLastName, $book->getAuthorLastName());
```
Comment (lchrusciel) [inline src/Bundle/test/src/Tests/Controller/ScienceBookUiTest.php:84]: From my experience, it is better to stay on the same level of tests for the execution of tests and their validation.

**Review by lchrusciel — APPROVED** [review]
